version: '3'
services:
  el6:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el6
    volumes:
      - .:/home/builduser/configsnap
      - ~/rpmbuild/RPMS:/home/builduser/rpmbuild/RPMS
      - ~/rpmbuild/SOURCES:/home/builduser/rpmbuild/SOURCES

  el7:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-el7
    volumes:
      - .:/home/builduser/configsnap
      - ~/rpmbuild/RPMS:/home/builduser/rpmbuild/RPMS
      - ~/rpmbuild/SOURCES:/home/builduser/rpmbuild/SOURCES

  fedora:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-fedora
    volumes:
      - .:/home/builduser/configsnap
      - ~/rpmbuild/RPMS:/home/builduser/rpmbuild/RPMS
      - ~/rpmbuild/SOURCES:/home/builduser/rpmbuild/SOURCES

  deb:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-deb
    volumes:
      - .:/home/builduser/configsnap
